<title>Tetsua Rakennus</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="style.css">
  <script src="https://kit.fontawesome.com/748de550fc.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=B612&display=swap" rel="stylesheet">
